# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cis454Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cis454Demo

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'	
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'

end
